package com.aovsa.bookingsApi.model.Business;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Model class to represent a business. <br>
 * A business has the following attributes: <br>
 * <ul>
 *     <li>id: Unique identifier for each business</li>
 *     <li>businessName: Commercial name for the business</li>
 *     <li>businessType: BusinessType</li>
 *     <li>description: Business description</li>
 *     <li>address: Address to business location</li>
 * </ul>
 * @version 1.0
 * @since 12-12-2023
 */
@Setter
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "BusinessTable")
public class BusinessModel {
    private String id;

    private String businessName;
//    private BusinessType businessType;
    private String description;
    private String address;
    @DynamoDBHashKey()
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    @DynamoDBAttribute
    public String getBusinessName() {
        return businessName;
    }
//    @DynamoDBAttribute
//    public BusinessType getBusinessType() {
//        return businessType;
//    }
    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }
    @DynamoDBAttribute
    public String getAddress() {
        return address;
    }
}
